const { createCrudRouter } = require('../utils/crudFactory');
const db = require('../models');
const schemas = require('../schemas');
const express = require('express');

// Auto-generated Business routes — DO NOT EDIT
const routers = [
    createCrudRouter('/account_categories', db['account_categories'], { schema: schemas['account_categories'] }),
    createCrudRouter('/addresses', db['addresses'], { schema: schemas['addresses'], viewName: 'v_addresses', sequelize: db.sequelize }),
    createCrudRouter('/allowance_types', db['allowance_types'], { schema: schemas['allowance_types'] }),
    createCrudRouter('/audit_logs', db['audit_logs'], { schema: schemas['audit_logs'] }),
    createCrudRouter('/audit_trail', db['audit_trail'], { sequelize: db.sequelize }),
    createCrudRouter('/amlio_reports', db['amlio_reports'], { sequelize: db.sequelize }),
    createCrudRouter('/bank_code', db['bank_code'], { schema: schemas['bank_code'], viewName: 'v_bank_code', sequelize: db.sequelize }),
    createCrudRouter('/bank_type', db['bank_type'], { schema: schemas['bank_type'] }),
    createCrudRouter('/borrower_connections', db['borrower_connections'], { schema: schemas['borrower_connections'] }),
    createCrudRouter('/borrowers_enterprise', db['borrowers_enterprise'], { schema: schemas['borrowers_enterprise'] }),
    createCrudRouter('/borrowers_individual', db['borrowers_individual'], { schema: schemas['borrowers_individual'] }),
    createCrudRouter('/careers', db['careers'], { schema: schemas['careers'] }),
    createCrudRouter('/categories', db['categories'], { schema: schemas['categories'] }),
    createCrudRouter('/collateral_categories', db['collateral_categories'], { schema: schemas['collateral_categories'] }),
    createCrudRouter('/collateral_enterprises', db['collateral_enterprises'], { schema: schemas['collateral_enterprises'], viewName: 'v_collateral_enterprises', sequelize: db.sequelize }),
    createCrudRouter('/collateral_individuals', db['collateral_individuals'], { schema: schemas['collateral_individuals'], viewName: 'v_collateral_individuals', sequelize: db.sequelize }),
    createCrudRouter('/collection_actions', db['collection_actions'], { schema: schemas['collection_actions'] }),
    createCrudRouter('/collection_case_assignments', db['collection_case_assignments'], { schema: schemas['collection_case_assignments'] }),
    createCrudRouter('/sms_escalation_rules', db['sms_escalation_rules'], { sequelize: db.sequelize }),
    createCrudRouter('/collection_escalation_rules', db['collection_escalation_rules'], { sequelize: db.sequelize }),
    createCrudRouter('/collaterals', db['collaterals'], { schema: schemas['collaterals'], viewName: 'v_collaterals', sequelize: db.sequelize }),
    createCrudRouter('/contact_details', db['contact_details'], { schema: schemas['contact_details'], viewName: 'v_contact_details', sequelize: db.sequelize }),
    createCrudRouter('/countries', db['countries'], { schema: schemas['countries'] }),
    createCrudRouter('/currencies', db['currencies'], { schema: schemas['currencies'] }),
    createCrudRouter('/customer_blacklists', db['customer_blacklists'], { schema: schemas['customer_blacklists'] }),
    createCrudRouter('/customer_types', db['customer_types'], { schema: schemas['customer_types'] }),
    createCrudRouter('/departments', db['departments'], { schema: schemas['departments'] }),
    createCrudRouter('/deposit_account_owners', db['deposit_account_owners'], { schema: schemas['deposit_account_owners'], viewName: 'v_deposit_account_owners', sequelize: db.sequelize }),
    createCrudRouter('/deposit_accounts', db['deposit_accounts'], { schema: schemas['deposit_accounts'], viewName: 'v_deposit_accounts', sequelize: db.sequelize }),
    createCrudRouter('/deposit_approval_history', db['deposit_approval_history'], { sequelize: db.sequelize }),
    createCrudRouter('/deposit_products', db['deposit_products'], { schema: schemas['deposit_products'], viewName: 'v_deposit_products', sequelize: db.sequelize }),
    createCrudRouter('/deposit_interest_accruals', db['deposit_interest_accruals'], { schema: schemas['deposit_interest_accruals'] }),
    createCrudRouter('/deposit_receipts', db['deposit_receipts'], { sequelize: db.sequelize }),
    createCrudRouter('/deposit_risk_scores', db['deposit_risk_scores'], { sequelize: db.sequelize }),
    createCrudRouter('/deposit_transactions', db['deposit_transactions'], { schema: schemas['deposit_transactions'], viewName: 'v_deposit_transactions', sequelize: db.sequelize }),
    createCrudRouter('/deposit_types', db['deposit_types'], { schema: schemas['deposit_types'] }),
    createCrudRouter('/country_risk_levels', db['country_risk_levels'], { sequelize: db.sequelize }),
    createCrudRouter('/districts', db['districts'], { schema: schemas['districts'], viewName: 'v_districts', sequelize: db.sequelize }),
    createCrudRouter('/ecl_parameters', db['ecl_parameters'], { schema: schemas['ecl_parameters'] }),
    createCrudRouter('/economic_branches', db['economic_branches'], { schema: schemas['economic_branches'] }),
    createCrudRouter('/economic_sectors', db['economic_sectors'], { schema: schemas['economic_sectors'] }),
    createCrudRouter('/educations', db['educations'], { schema: schemas['educations'] }),
    createCrudRouter('/employee_allowances', db['employee_allowances'], { schema: schemas['employee_allowances'], viewName: 'v_employee_allowances', sequelize: db.sequelize }),
    createCrudRouter('/employee_assignments', db['employee_assignments'], { schema: schemas['employee_assignments'], viewName: 'v_employee_assignments', sequelize: db.sequelize }),
    createCrudRouter('/employee_branch_assignments', db['employee_branch_assignments'], { schema: schemas['employee_branch_assignments'] }),
    createCrudRouter('/employee_positions', db['employee_positions'], { schema: schemas['employee_positions'], viewName: 'v_employee_positions', sequelize: db.sequelize }),
    createCrudRouter('/employees', db['employees'], { schema: schemas['employees'], viewName: 'v_employees', sequelize: db.sequelize }),
    createCrudRouter('/employment_contracts', db['employment_contracts'], { schema: schemas['employment_contracts'], viewName: 'v_employment_contracts', sequelize: db.sequelize }),
    createCrudRouter('/enterprise_categories', db['enterprise_categories'], { schema: schemas['enterprise_categories'] }),
    createCrudRouter('/enterprise_info', db['enterprise_info'], { schema: schemas['enterprise_info'] }),
    createCrudRouter('/enterprise_model_details', db['enterprise_model_details'], { schema: schemas['enterprise_model_details'], viewName: 'v_enterprise_model_details', sequelize: db.sequelize }),
    createCrudRouter('/enterprise_models', db['enterprise_models'], { schema: schemas['enterprise_models'] }),
    createCrudRouter('/enterprise_sizes', db['enterprise_sizes'], { schema: schemas['enterprise_sizes'] }),
    createCrudRouter('/enterprise_stakeholder_roles', db['enterprise_stakeholder_roles'], { schema: schemas['enterprise_stakeholder_roles'] }),
    createCrudRouter('/enterprise_stakeholders', db['enterprise_stakeholders'], { schema: schemas['enterprise_stakeholders'], viewName: 'v_enterprise_stakeholders', sequelize: db.sequelize }),
    createCrudRouter('/enterprise_types', db['enterprise_types'], { schema: schemas['enterprise_types'] }),
    createCrudRouter('/exchange_rates', db['exchange_rates'], { schema: schemas['exchange_rates'] }),
    createCrudRouter('/family_books', db['family_books'], { schema: schemas['family_books'], viewName: 'v_family_books', sequelize: db.sequelize }),
    createCrudRouter('/financial_statement_lines', db['financial_statement_lines'], { schema: schemas['financial_statement_lines'], viewName: 'v_financial_statement_lines', sequelize: db.sequelize }),
    createCrudRouter('/financial_statements', db['financial_statements'], { schema: schemas['financial_statements'], viewName: 'v_financial_statements', sequelize: db.sequelize }),
    createCrudRouter('/fiscal_periods', db['fiscal_periods'], { schema: schemas['fiscal_periods'] }),
    createCrudRouter('/genders', db['genders'], { schema: schemas['genders'] }),
    createCrudRouter('/gl_balances', db['gl_balances'], { schema: schemas['gl_balances'], viewName: 'v_gl_balances', sequelize: db.sequelize }),
    createCrudRouter('/health_insurance', db['health_insurance'], { schema: schemas['health_insurance'], viewName: 'v_health_insurance', sequelize: db.sequelize }),
    createCrudRouter('/iif_collateral_details', db['iif_collateral_details'], { schema: schemas['iif_collateral_details'], viewName: 'v_iif_collateral_details', sequelize: db.sequelize }),
    createCrudRouter('/iif_cosigners', db['iif_cosigners'], { schema: schemas['iif_cosigners'], viewName: 'v_iif_cosigners', sequelize: db.sequelize }),
    createCrudRouter('/iif_enterprise_details', db['iif_enterprise_details'], { schema: schemas['iif_enterprise_details'], viewName: 'v_iif_enterprise_details', sequelize: db.sequelize }),
    createCrudRouter('/iif_headers', db['iif_headers'], { schema: schemas['iif_headers'] }),
    createCrudRouter('/iif_individual_details', db['iif_individual_details'], { schema: schemas['iif_individual_details'], viewName: 'v_iif_individual_details', sequelize: db.sequelize }),
    createCrudRouter('/iif_loan_details', db['iif_loan_details'], { schema: schemas['iif_loan_details'], viewName: 'v_iif_loan_details', sequelize: db.sequelize }),
    createCrudRouter('/individual_groups', db['individual_groups'], { schema: schemas['individual_groups'], viewName: 'v_individual_groups', sequelize: db.sequelize }),
    createCrudRouter('/interest_configs', db['interest_configs'], { schema: schemas['interest_configs'] }),
    createCrudRouter('/it_fee_configs', db['it_fee_configs'], { schema: schemas['it_fee_configs'] }),
    createCrudRouter('/jdb_http_logs', db['jdb_http_logs'], { schema: schemas['jdb_http_logs'] }),
    createCrudRouter('/jdb_transactions', db['jdb_transactions'], { schema: schemas['jdb_transactions'] }),
    createCrudRouter('/key_personnels', db['key_personnels'], { schema: schemas['key_personnels'] }),
    createCrudRouter('/land_size_units', db['land_size_units'], { schema: schemas['land_size_units'], idField: 'code' }),
    createCrudRouter('/lao_id_cards', db['lao_id_cards'], { schema: schemas['lao_id_cards'], viewName: 'v_lao_id_cards', sequelize: db.sequelize }),
    createCrudRouter('/leave_balances', db['leave_balances'], { schema: schemas['leave_balances'], viewName: 'v_leave_balances', sequelize: db.sequelize }),
    createCrudRouter('/leave_requests', db['leave_requests'], { schema: schemas['leave_requests'], viewName: 'v_leave_requests', sequelize: db.sequelize }),
    createCrudRouter('/leave_types', db['leave_types'], { schema: schemas['leave_types'] }),
    createCrudRouter('/loan_applications', db['loan_applications'], { schema: schemas['loan_applications'] }),
    createCrudRouter('/loan_approval_history', db['loan_approval_history'], { schema: schemas['loan_approval_history'], viewName: 'v_loan_approval_history', sequelize: db.sequelize }),
    createCrudRouter('/loan_approval_limits', db['loan_approval_limits'], { schema: schemas['loan_approval_limits'], viewName: 'v_loan_approval_limits', sequelize: db.sequelize }),
    createCrudRouter('/loan_categories', db['loan_categories'], { schema: schemas['loan_categories'] }),
    createCrudRouter('/loan_classifications', db['loan_classifications'], { schema: schemas['loan_classifications'] }),
    createCrudRouter('/loan_collaterals', db['loan_collaterals'], { schema: schemas['loan_collaterals'], viewName: 'v_loan_collaterals', sequelize: db.sequelize }),
    createCrudRouter('/loan_contracts', db['loan_contracts'], { schema: schemas['loan_contracts'], viewName: 'v_loan_contracts', sequelize: db.sequelize }),
    createCrudRouter('/loan_ecl_staging', db['loan_ecl_staging'], { schema: schemas['loan_ecl_staging'] }),
    createCrudRouter('/loan_fees', db['loan_fees'], { schema: schemas['loan_fees'] }),
    createCrudRouter('/loan_funding_sources', db['loan_funding_sources'], { schema: schemas['loan_funding_sources'] }),
    createCrudRouter('/loan_insurance', db['loan_insurance'], { schema: schemas['loan_insurance'] }),
    createCrudRouter('/loan_products', db['loan_products'], { schema: schemas['loan_products'], viewName: 'v_loan_products', sequelize: db.sequelize }),
    createCrudRouter('/loan_purpose', db['loan_purpose'], { schema: schemas['loan_purpose'] }),
    createCrudRouter('/loan_repayment_schedules', db['loan_repayment_schedules'], { schema: schemas['loan_repayment_schedules'], viewName: 'v_loan_repayment_schedules', sequelize: db.sequelize }),
    createCrudRouter('/loan_terms', db['loan_terms'], { schema: schemas['loan_terms'] }),
    createCrudRouter('/loan_transactions', db['loan_transactions'], { schema: schemas['loan_transactions'], viewName: 'v_loan_transactions', sequelize: db.sequelize }),
    createCrudRouter('/loan_types', db['loan_types'], { schema: schemas['loan_types'] }),
    createCrudRouter('/marital_statuses', db['marital_statuses'], { schema: schemas['marital_statuses'] }),
    createCrudRouter('/marriages', db['marriages'], { schema: schemas['marriages'], viewName: 'v_marriages', sequelize: db.sequelize }),
    createCrudRouter('/member_shares', db['member_shares'], { schema: schemas['member_shares'], viewName: 'v_member_shares', sequelize: db.sequelize }),
    createCrudRouter('/member_shares_enterprises', db['member_shares_enterprises'], { schema: schemas['member_shares_enterprises'], viewName: 'v_member_shares_enterprises', sequelize: db.sequelize }),
    createCrudRouter('/member_shares_individuals', db['member_shares_individuals'], { schema: schemas['member_shares_individuals'], viewName: 'v_member_shares_individuals', sequelize: db.sequelize }),
    createCrudRouter('/menu_items', db['menu_items'], { schema: schemas['menu_items'] }),
    createCrudRouter('/mfi_branch_service_units', db['mfi_branch_service_units'], { schema: schemas['mfi_branch_service_units'], viewName: 'v_mfi_branch_service_units', sequelize: db.sequelize }),
    createCrudRouter('/mfi_branches_info', db['mfi_branches_info'], { schema: schemas['mfi_branches_info'] }),
    createCrudRouter('/mfi_hq_service_units', db['mfi_hq_service_units'], { schema: schemas['mfi_hq_service_units'], viewName: 'v_mfi_hq_service_units', sequelize: db.sequelize }),
    createCrudRouter('/mfi_info', db['mfi_info'], { schema: schemas['mfi_info'] }),
    createCrudRouter('/mfi_service_units_info', db['mfi_service_units_info'], { schema: schemas['mfi_service_units_info'] }),
    createCrudRouter('/nationality', db['nationality'], { schema: schemas['nationality'], idField: 'nationality_id' }),
    createCrudRouter('/notifications', db['notifications'], { schema: schemas['notifications'] }),
    createCrudRouter('/org_branches', db['org_branches'], { schema: schemas['org_branches'] }),
    createCrudRouter('/organizations', db['organizations'], { schema: schemas['organizations'], idField: 'code' }),
    createCrudRouter('/overtime_records', db['overtime_records'], { schema: schemas['overtime_records'], viewName: 'v_overtime_records', sequelize: db.sequelize }),
    createCrudRouter('/passports', db['passports'], { schema: schemas['passports'], viewName: 'v_passports', sequelize: db.sequelize }),
    createCrudRouter('/payroll_details', db['payroll_details'], { schema: schemas['payroll_details'] }),
    createCrudRouter('/payrolls', db['payrolls'], { schema: schemas['payrolls'], viewName: 'v_payrolls', sequelize: db.sequelize }),
    createCrudRouter('/period_close_log', db['period_close_log'], { schema: schemas['period_close_log'], viewName: 'v_period_close_log', sequelize: db.sequelize }),
    createCrudRouter('/permissions', db['permissions'], { schema: schemas['permissions'] }),
    createCrudRouter('/personal_info', db['personal_info'], { schema: schemas['personal_info'] }),
    createCrudRouter('/personal_relationships', db['personal_relationships'], { schema: schemas['personal_relationships'], viewName: 'v_personal_relationships', sequelize: db.sequelize }),
    createCrudRouter('/personal_surname_history', db['personal_surname_history'], { schema: schemas['personal_surname_history'], viewName: 'v_personal_surname_history', sequelize: db.sequelize }),
    createCrudRouter('/promise_to_pay', db['promise_to_pay'], { schema: schemas['promise_to_pay'] }),
    createCrudRouter('/provinces', db['provinces'], { schema: schemas['provinces'], viewName: 'v_provinces', sequelize: db.sequelize }),
    createCrudRouter('/report_info', db['report_info'], { schema: schemas['report_info'] }),
    createCrudRouter('/role_menus', db['role_menus'], { schema: schemas['role_menus'] }),
    createCrudRouter('/role_permissions', db['role_permissions'], { schema: schemas['role_permissions'], viewName: 'v_role_permissions', sequelize: db.sequelize }),
    createCrudRouter('/roles', db['roles'], { schema: schemas['roles'] }),
    createCrudRouter('/salary_grades', db['salary_grades'], { schema: schemas['salary_grades'] }),
    createCrudRouter('/staff_compliance', db['staff_compliance'], { schema: schemas['staff_compliance'], viewName: 'v_staff_compliance', sequelize: db.sequelize }),
    createCrudRouter('/tax_brackets', db['tax_brackets'], { schema: schemas['tax_brackets'] }),
    createCrudRouter('/trainings', db['trainings'], { schema: schemas['trainings'], viewName: 'v_trainings', sequelize: db.sequelize }),
    createCrudRouter('/user_roles', db['user_roles'], { schema: schemas['user_roles'], viewName: 'v_user_roles', sequelize: db.sequelize }),
    createCrudRouter('/users', db['users'], { schema: schemas['users'], viewName: 'v_users', sequelize: db.sequelize }),
    createCrudRouter('/v_borrower_loans', db['v_borrower_loans'], { schema: schemas['v_borrower_loans'] }),
    createCrudRouter('/villages', db['villages'], { schema: schemas['villages'], viewName: 'v_villages', sequelize: db.sequelize })
];

const router = express.Router();
routers.forEach(r => { if (r && r.stack) router.use(r); });

module.exports = router;
