/**
 * meta.routes.js — Form Metadata API
 * 
 * GET /api/meta          → ລາຍຊື່ tables ທັງໝົດ ພ້ອມ metadata
 * GET /api/meta/:table   → metadata ລະອຽດ ຂອງ 1 table (fields, grid, form config)
 */
const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const db = require('../models');

// Load blueprint (generated by pipeline.js)
let blueprint = {};
const blueprintPath = path.join(__dirname, '../../frontend-blueprint.json');
try {
    if (fs.existsSync(blueprintPath)) {
        blueprint = JSON.parse(fs.readFileSync(blueprintPath, 'utf8'));
    }
} catch (err) {
    console.error('⚠️ Failed to load frontend-blueprint.json:', err.message);
}

// ─── Cascading field definitions ───
// ກຳນົດ fields ທີ່ຕ້ອງ cascading (parent → child)
const CASCADING_CONFIG = {
    province_id: {
        childFields: ['district_id'],
        optionsTable: '_provinces',
    },
    district_id: {
        dependsOn: 'province_id',
        filterKey: 'province_id',
        childFields: ['village_id'],
        optionsTable: '_districts',
    },
    village_id: {
        dependsOn: 'district_id',
        filterKey: 'district_id',
        optionsTable: '_villages',
    },
};

// GET /api/meta — ລາຍຊື່ tables ທັງໝົດ
router.get('/meta', (req, res) => {
    const tables = Object.entries(blueprint).map(([name, info]) => ({
        tableName: name,
        modelName: info.modelName,
        category: info.category,
        columnCount: info.columnCount,
        apiEndpoint: info.apiEndpoint,
        hasTimestamps: info.hasTimestamps,
    }));
    res.json({ data: tables, total: tables.length, status: true });
});

// GET /api/meta/:table — metadata ລະອຽດ ຂອງ 1 table
router.get('/meta/:table', async (req, res) => {
    const { table } = req.params;
    const meta = blueprint[table];

    if (!meta) {
        return res.status(404).json({ message: `Table '${table}' not found`, status: false });
    }

    // Resolve FK options: ดึง dropdown data จาก dictionary tables
    const enrichedFormFields = await Promise.all(
        meta.formFields.map(async (field) => {
            const fkTable = field.fkTable || field.likelyFkTable;
            const displayField = field.fkDisplayField || 'value';

            if (field.type === 'select' && fkTable) {
                // Try to fetch options from the FK table
                const model = db[fkTable] || db[`_${fkTable}`] || db[`_${fkTable}s`];
                if (model) {
                    try {
                        const rows = await model.findAll({
                            attributes: ['id', displayField],
                            order: [['id', 'ASC']],
                            limit: 500,
                        });
                        return {
                            ...field,
                            options: rows.map(r => ({
                                value: r.id,
                                label: r[displayField] || `#${r.id}`,
                            })),
                        };
                    } catch (err) {
                        // FK table doesn't have expected columns
                        return { ...field, options: [] };
                    }
                }
            }
            return field;
        })
    );

    // ② Inject cascading config into fields
    const finalFields = enrichedFormFields.map(field => {
        const cascade = CASCADING_CONFIG[field.name];
        if (cascade) {
            return {
                ...field,
                dependsOn: cascade.dependsOn || null,
                filterKey: cascade.filterKey || null,
                optionsUrl: cascade.dependsOn
                    ? `/meta/options/${cascade.optionsTable}?filterKey=${cascade.filterKey}`
                    : null,
            };
        }
        return field;
    });

    res.json({
        ...meta,
        formFields: finalFields,
        status: true,
    });
});

// GET /api/meta/options/:table?filterKey=province_id&filterValue=1
// ━━━ Cascading dropdown: ດຶງ options ທີ່ filter ຕາມ parent ━━━
router.get('/meta/options/:table', async (req, res) => {
    try {
        const { table } = req.params;
        const { filterKey, filterValue } = req.query;

        const model = db[table] || db[`_${table}`];
        if (!model) {
            return res.status(404).json({ message: `Table '${table}' not found` });
        }

        const where = {};
        if (filterKey && filterValue) {
            where[filterKey] = filterValue;
        }

        const rows = await model.findAll({
            attributes: ['id', 'value'],
            where,
            order: [['id', 'ASC']],
            limit: 500,
        });

        res.json({
            data: rows.map(r => ({ value: r.id, label: r.value || `#${r.id}` })),
            status: true,
        });
    } catch (err) {
        res.status(500).json({ message: err.message });
    }
});

module.exports = router;
