module.exports = (sequelize, DataTypes) => {
    return sequelize.define('borrowers_individual', {
        id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
        borrower_id: { type: DataTypes.INTEGER, allowNull: false },
        loan_id: { type: DataTypes.INTEGER },
        personal_info_id: { type: DataTypes.INTEGER },
        firstname__l_a: { type: DataTypes.STRING(255) },
        lastname__l_a: { type: DataTypes.STRING(255) },
        firstname__e_n: { type: DataTypes.STRING(255) },
        lastname__e_n: { type: DataTypes.STRING(255) },
        dateofbirth: { type: DataTypes.DATEONLY },
        gender_id: { type: DataTypes.INTEGER },
        nationality_id: { type: DataTypes.INTEGER },
        marital_status_id: { type: DataTypes.INTEGER },
        career_id: { type: DataTypes.INTEGER },
        village_id: { type: DataTypes.INTEGER },
        home_address: { type: DataTypes.STRING(255) },
        contact_info: { type: DataTypes.STRING(255) },
        mobile_no: { type: DataTypes.STRING(255) },
        telephone_no: { type: DataTypes.STRING(255) },
        country_id: { type: DataTypes.INTEGER },
        card_id: { type: DataTypes.INTEGER },
        card_no: { type: DataTypes.STRING(255) },
        card_name: { type: DataTypes.STRING(255) },
        card_date_of_issue: { type: DataTypes.DATEONLY },
        card_exp_date: { type: DataTypes.DATEONLY },
        spouse_id: { type: DataTypes.INTEGER },
        spouse_name_1st__e_n: { type: DataTypes.STRING(255) },
        spouse_surname__e_n: { type: DataTypes.STRING(255) },
        spouse_name__l_a: { type: DataTypes.STRING(255) },
        spouse_surname__l_a: { type: DataTypes.STRING(255) },
        spouse_mobile_no: { type: DataTypes.STRING(255) },
        book_id: { type: DataTypes.INTEGER },
        book_no: { type: DataTypes.STRING(255) },
        book_name: { type: DataTypes.STRING(255) },
        book_date_of_issue: { type: DataTypes.DATEONLY },
        book_village_id: { type: DataTypes.INTEGER },
        passport_id: { type: DataTypes.INTEGER },
        passport_no: { type: DataTypes.STRING(255) },
        passport_name: { type: DataTypes.STRING(255) },
        passport_exp_date: { type: DataTypes.DATEONLY },
        firstname_la: { type: DataTypes.STRING(255) },
        lastname_la: { type: DataTypes.STRING(255) },
        firstname_en: { type: DataTypes.STRING(255) },
        lastname_en: { type: DataTypes.STRING(255) },
        spouse_name_1st_en: { type: DataTypes.STRING(255) },
        spouse_surname_en: { type: DataTypes.STRING(255) },
        spouse_name_la: { type: DataTypes.STRING(255) },
        spouse_surname_la: { type: DataTypes.STRING(255) }
    }, { tableName: 'borrowers_individual', timestamps: false });
};
