module.exports = (sequelize, DataTypes) => {
    return sequelize.define('loan_contracts', {
        id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
        contract_no: { type: DataTypes.STRING(50), allowNull: false, unique: true },
        product_id: { type: DataTypes.INTEGER },
        currency_id: { type: DataTypes.INTEGER },
        approved_amount: { type: DataTypes.DECIMAL(20, 2), allowNull: false },
        interest_rate: { type: DataTypes.DECIMAL(5, 2), allowNull: false },
        term_months: { type: DataTypes.INTEGER, allowNull: false },
        disbursement_date: { type: DataTypes.DATEONLY },
        maturity_date: { type: DataTypes.DATEONLY },
        loan_purpose_id: { type: DataTypes.INTEGER },
        loan_status: { type: DataTypes.STRING(20), defaultValue: 'PENDING' },
        created_at: { type: DataTypes.DATE },
        updated_at: { type: DataTypes.DATE },
        classification_id: { type: DataTypes.INTEGER },
        classification_date: { type: DataTypes.DATEONLY },
        economic_sector_id: { type: DataTypes.INTEGER },
        economic_branch_id: { type: DataTypes.INTEGER },
        borrower_type_id: { type: DataTypes.INTEGER },
        borrower_connection_id: { type: DataTypes.INTEGER },
        funding_source_id: { type: DataTypes.INTEGER },
        remaining_balance: { type: DataTypes.DECIMAL(20, 2) },
        days_past_due: { type: DataTypes.INTEGER, defaultValue: 0 },
        loan_type_id: { type: DataTypes.INTEGER },
        loan_term_id: { type: DataTypes.INTEGER },
        use_of_loan: { type: DataTypes.TEXT },
        allowance_losses: { type: DataTypes.DECIMAL(20, 2) },
        restructured_date: { type: DataTypes.DATEONLY },
        write_off_date: { type: DataTypes.DATEONLY },
        extension_date: { type: DataTypes.DATEONLY },
        funding_org: { type: DataTypes.STRING(1000) },
        deleted_at: { type: DataTypes.DATE }
    }, { tableName: 'loan_contracts', createdAt: 'created_at', updatedAt: 'updated_at' });
};
