const { z } = require('zod');

// ===== borrowers_individual =====

const createSchema = z.object({
    borrower_id: z.number().int(),
    loan_id: z.number().int().optional().nullable(),
    personal_info_id: z.number().int().optional().nullable(),
    firstname__l_a: z.string().max(255).optional().nullable(),
    lastname__l_a: z.string().max(255).optional().nullable(),
    firstname__e_n: z.string().max(255).optional().nullable(),
    lastname__e_n: z.string().max(255).optional().nullable(),
    dateofbirth: z.string().optional().nullable(),
    gender_id: z.number().int().optional().nullable(),
    nationality_id: z.number().int().optional().nullable(),
    marital_status_id: z.number().int().optional().nullable(),
    career_id: z.number().int().optional().nullable(),
    village_id: z.number().int().optional().nullable(),
    home_address: z.string().max(255).optional().nullable(),
    contact_info: z.string().max(255).optional().nullable(),
    mobile_no: z.string().max(255).optional().nullable(),
    telephone_no: z.string().max(255).optional().nullable(),
    country_id: z.number().int().optional().nullable(),
    card_id: z.number().int().optional().nullable(),
    card_no: z.string().max(255).optional().nullable(),
    card_name: z.string().max(255).optional().nullable(),
    card_date_of_issue: z.string().optional().nullable(),
    card_exp_date: z.string().optional().nullable(),
    spouse_id: z.number().int().optional().nullable(),
    spouse_name_1st__e_n: z.string().max(255).optional().nullable(),
    spouse_surname__e_n: z.string().max(255).optional().nullable(),
    spouse_name__l_a: z.string().max(255).optional().nullable(),
    spouse_surname__l_a: z.string().max(255).optional().nullable(),
    spouse_mobile_no: z.string().max(255).optional().nullable(),
    book_id: z.number().int().optional().nullable(),
    book_no: z.string().max(255).optional().nullable(),
    book_name: z.string().max(255).optional().nullable(),
    book_date_of_issue: z.string().optional().nullable(),
    book_village_id: z.number().int().optional().nullable(),
    passport_id: z.number().int().optional().nullable(),
    passport_no: z.string().max(255).optional().nullable(),
    passport_name: z.string().max(255).optional().nullable(),
    passport_exp_date: z.string().optional().nullable(),
    firstname_la: z.string().max(255).optional().nullable(),
    lastname_la: z.string().max(255).optional().nullable(),
    firstname_en: z.string().max(255).optional().nullable(),
    lastname_en: z.string().max(255).optional().nullable(),
    spouse_name_1st_en: z.string().max(255).optional().nullable(),
    spouse_surname_en: z.string().max(255).optional().nullable(),
    spouse_name_la: z.string().max(255).optional().nullable(),
    spouse_surname_la: z.string().max(255).optional().nullable()
});

const updateSchema = createSchema.partial();

const querySchema = z.object({
    id: z.number().int().optional().nullable(),
    borrower_id: z.number().int(),
    loan_id: z.number().int().optional().nullable(),
    personal_info_id: z.number().int().optional().nullable(),
    firstname__l_a: z.string().max(255).optional().nullable(),
    lastname__l_a: z.string().max(255).optional().nullable(),
    firstname__e_n: z.string().max(255).optional().nullable(),
    lastname__e_n: z.string().max(255).optional().nullable(),
    dateofbirth: z.string().optional().nullable(),
    gender_id: z.number().int().optional().nullable(),
    nationality_id: z.number().int().optional().nullable(),
    marital_status_id: z.number().int().optional().nullable(),
    career_id: z.number().int().optional().nullable(),
    village_id: z.number().int().optional().nullable(),
    home_address: z.string().max(255).optional().nullable(),
    contact_info: z.string().max(255).optional().nullable(),
    mobile_no: z.string().max(255).optional().nullable(),
    telephone_no: z.string().max(255).optional().nullable(),
    country_id: z.number().int().optional().nullable(),
    card_id: z.number().int().optional().nullable(),
    card_no: z.string().max(255).optional().nullable(),
    card_name: z.string().max(255).optional().nullable(),
    card_date_of_issue: z.string().optional().nullable(),
    card_exp_date: z.string().optional().nullable(),
    spouse_id: z.number().int().optional().nullable(),
    spouse_name_1st__e_n: z.string().max(255).optional().nullable(),
    spouse_surname__e_n: z.string().max(255).optional().nullable(),
    spouse_name__l_a: z.string().max(255).optional().nullable(),
    spouse_surname__l_a: z.string().max(255).optional().nullable(),
    spouse_mobile_no: z.string().max(255).optional().nullable(),
    book_id: z.number().int().optional().nullable(),
    book_no: z.string().max(255).optional().nullable(),
    book_name: z.string().max(255).optional().nullable(),
    book_date_of_issue: z.string().optional().nullable(),
    book_village_id: z.number().int().optional().nullable(),
    passport_id: z.number().int().optional().nullable(),
    passport_no: z.string().max(255).optional().nullable(),
    passport_name: z.string().max(255).optional().nullable(),
    passport_exp_date: z.string().optional().nullable(),
    firstname_la: z.string().max(255).optional().nullable(),
    lastname_la: z.string().max(255).optional().nullable(),
    firstname_en: z.string().max(255).optional().nullable(),
    lastname_en: z.string().max(255).optional().nullable(),
    spouse_name_1st_en: z.string().max(255).optional().nullable(),
    spouse_surname_en: z.string().max(255).optional().nullable(),
    spouse_name_la: z.string().max(255).optional().nullable(),
    spouse_surname_la: z.string().max(255).optional().nullable()
}).partial();

module.exports = {
    createSchema,
    updateSchema,
    querySchema,
    tableName: 'borrowers_individual',
};
