const { z } = require('zod');

const lmpsTransactionsSchema = z.object({
    direction: z.enum(['OUTGOING', 'INCOMING']).optional(),
    command_type: z.enum(['INQUIRY', 'TRANSFER', 'NOTIFY']).optional(),
    lapnet_transaction_id: z.string().max(64).optional().nullable(),
    from_member: z.string().max(16).optional(),
    from_user: z.string().max(64).optional().nullable(),
    from_user_fullname: z.string().max(256).optional().nullable(),
    from_account: z.string().max(32).optional().nullable(),
    from_account_type: z.string().max(64).optional().nullable(),
    to_type: z.string().max(16).optional().nullable(),
    to_account: z.string().optional().nullable(),
    to_member: z.string().max(16).optional().nullable(),
    reference: z.string().max(64).optional(),
    amount: z.number().optional().nullable(),
    fee: z.number().optional().nullable(),
    ccy: z.string().max(3).optional().nullable(),
    purpose: z.string().max(512).optional().nullable(),
    request_time: z.string().max(25).optional().nullable(),
    result: z.string().max(64).optional().nullable(),
    receipt: z.string().max(64).optional().nullable(),
    should_revert: z.number().optional().nullable(),
    response_time: z.string().max(25).optional().nullable(),
    account_name: z.string().max(128).optional().nullable(),
    account_ccy: z.string().max(16).optional().nullable(),
    fee_list: z.string().optional().nullable(),
    source_signature: z.string().optional().nullable(),
    lapnet_request_signature: z.string().optional().nullable(),
    destination_signature: z.string().optional().nullable(),
    lapnet_response_signature: z.string().optional().nullable(),
    contract_id: z.number().optional().nullable(),
    installment_no: z.number().optional().nullable(),
    branch_id: z.string().max(50).optional().nullable(),
    deposit_account_id: z.number().optional().nullable(),
    exchange_rate: z.number().optional().nullable(),
    dst_amount: z.number().optional().nullable(),
    dst_ccy: z.string().max(3).optional().nullable(),
    src_amount: z.number().optional().nullable(),
    src_ccy: z.string().max(3).optional().nullable(),
    raw_request: z.string().optional().nullable(),
    raw_response: z.string().optional().nullable(),
    retry_count: z.number().optional().nullable(),
    status: z.enum(['PENDING', 'PROCESSING', 'SUCCESS', 'FAILED']).optional(),
});

module.exports = { lmpsTransactionsSchema };
